name: tim_apel
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  colours: ^0.0.2
  cupertino_icons: ^1.0.2
  currency_text_input_formatter: ^2.1.10
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.0
  flutter_secure_storage: ^8.0.0
  flutter_segment: ^3.13.0
  flutter_speed_dial: ^7.0.0
  fluttertoast: ^8.2.2
  image_picker: ^1.0.0
  input_quantity: ^1.1.6
  intl: ^0.18.1

  path_provider: ^2.0.15
  provider: ^6.0.5
  qr_flutter: ^4.1.0
  quickalert: ^1.0.1
  syncfusion_flutter_charts: ^21.1.41
  syncfusion_flutter_datepicker: ^21.2.10

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#B2DFDB"
  image: "assets/images/splash-02.png"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/register-done.png
    - assets/images/splash-02.png
    - assets/product_images/produk_1.jpg
    - assets/product_images/produk_2.jpg
    - assets/product_images/produk_3.jpg
    - assets/product_images/produk_4.jpg
    - assets/product_images/produk_5.jpg
    - assets/product_images/produk_6.jpg
    - assets/profile_pictures/picture-1.png
    - assets/profile_pictures/picture-2.png
    - assets/profile_pictures/picture-3.png
    - assets/profile_pictures/picture-4.png
    - assets/profile_pictures/picture-5.png
    - assets/profile_pictures/picture-6.png
    - assets/profile_pictures/picture-7.png
    - assets/profile_pictures/picture-8.png
    - assets/profile_pictures/picture-9.png
    - assets/profile_pictures/picture-10.png
    - assets/payment/tunai-logo_text.png
    - assets/payment/ovo-logo.png
    - assets/payment/ovo-logo_text.png
    - assets/payment/gopay-logo.png
    - assets/payment/gopay-logo_text.png
    - assets/payment/shopeepay-logo.png
    - assets/payment/shopeepay-logo_text.png
    - assets/payment/dana-logo.png
    - assets/payment/dana-logo_text.png
    - assets/payment/payment-done.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Figtree
      fonts:
        - asset: fonts/Figtree/Figtree-Black.ttf
          weight: 900

        - asset: fonts/Figtree/Figtree-BlackItalic.ttf
          weight: 900
          style: italic

        - asset: fonts/Figtree/Figtree-Bold.ttf
          weight: 700

        - asset: fonts/Figtree/Figtree-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: fonts/Figtree/Figtree-ExtraBold.ttf
          weight: 800

        - asset: fonts/Figtree/Figtree-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        - asset: fonts/Figtree/Figtree-Italic.ttf
          style: italic

        - asset: fonts/Figtree/Figtree-Light.ttf
          weight: 300

        - asset: fonts/Figtree/Figtree-LightItalic.ttf
          weight: 300
          style: italic

        - asset: fonts/Figtree/Figtree-LightItalic.ttf
          weight: 300
          style: italic

        - asset: fonts/Figtree/Figtree-Medium.ttf
          weight: 500

        - asset: fonts/Figtree/Figtree-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: fonts/Figtree/Figtree-Regular.ttf
          weight: 400

        - asset: fonts/Figtree/Figtree-SemiBold.ttf
          weight: 600

        - asset: fonts/Figtree/Figtree-SemiBoldItalic.ttf
          weight: 600
          style: italic

    - family: Plus Jakarta Sans
      fonts:
        - asset: fonts/Plus_Jakarta_Sans/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: fonts/Plus_Jakarta_Sans/PlusJakartaSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Plus_Jakarta_Sans/PlusJakartaSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/Plus_Jakarta_Sans/PlusJakartaSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Plus_Jakarta_Sans/PlusJakartaSans-ExtraLight.ttf
          weight: 200
        - asset: fonts/Plus_Jakarta_Sans/PlusJakartaSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Plus_Jakarta_Sans/PlusJakartaSans-Italic.ttf
          style: italic
        - asset: fonts/Plus_Jakarta_Sans/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: fonts/Plus_Jakarta_Sans/PlusJakartaSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Plus_Jakarta_Sans/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: fonts/Plus_Jakarta_Sans/PlusJakartaSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Plus_Jakarta_Sans/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: fonts/Plus_Jakarta_Sans/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: fonts/Plus_Jakarta_Sans/PlusJakartaSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
